### ISSUE TITLE
SubwordFeaturizer.iextract not word for vietnamese

### ISSUE THREAD

**Issue by namdn** [TensorSpeech/TensorFlowASR#169] opened 2021-03-30 08:30 UTC
When I test `test_subword_conformer.py` I see `SubwordFeaturizer.iextract` is not correct for Vietnamese character. So I write a small script to test extract and iextract, and found that the result is not the same. this is my snippet:

```
text_featurizer = SubwordFeaturizer.load_from_file(config.decoder_config, '/home/amin/Desktop/ASR/TensorFlowASR/vivos/vivos.subwords')
text = u'hôm nay trời đẹp quá'
encode = text_featurizer.extract(text)
print(encode, encode.shape)
decode = ''.join(text_featurizer.subwords.decode(encode))
print(decode)
print(bytes(decode, 'utf-8'))
decode = text_featurizer.iextract(tf.expand_dims(encode, axis=0))
print(bytes.decode(decode[0].numpy(), encoding='utf-8'))
```
And the result here:
```
tf.Tensor(
[3929 4020 4005 3934 3857 3935 3922 3946 3857 3941 3939 4050 4012 3982
 3930 3857 4021 3970 4050 4011 4010 3937 3857 3938 3942 4020 3986], shape=(27,), dtype=int32) (27,)
hôm nay trời đẹp quá
b'h\xc3\xb4m nay tr\xe1\xbb\x9di \xc4\x91\xe1\xba\xb9p qu\xc3\xa1'
h��m nay tr���i �����p qu��
```

**Comment by namdn** [comment] 2021-03-31 03:19
Here you are. I built it from vivos dataset.
[vivos.zip](https://github.com/TensorSpeech/TensorFlowASR/files/6233583/vivos.zip)

**Comment by usimarit** [comment] 2021-03-31 12:33
@namdn The issue is reproduced, meanwhile, can you try the [TFSubwordFeaturizer](https://github.com/TensorSpeech/TensorFlowASR/blob/283d1f2df3a4da021721c222a51c1e4bbc709238/tensorflow_asr/featurizers/text_featurizers.py#L326)?

**Comment by usimarit** [comment] 2021-04-03 18:13
@namdn Oh sorry the `TFSubwordFeaturizer` is not completed, you can use the fixed version of `SubwordFeaturizer` on branch `dev/transducer`

**Comment by usimarit** [comment] 2022-09-02 05:45
I’ll close the issue here due to new version of subword/wordpiece will be used.
I’ll test with vietnamese dataset and feedback on the readme of the repo.
Feel free to reopen if you have further questions.

**Closed by usimarit** 2022-09-02 05:45 UTC
